### PR TITLE
Redstone improvements [SEE DESC]

### LINKED ISSUE #1083: Redstone wires arent updated within 1 Tick
As i tested the redstone simulator, i found the bug, that a line from 15 redstone isn't udated within 1 tick, see the following gif. (this isnt a copy from #860, because this bug is that redstone isnt updated within 1 tick and #860 is that redstone isnt updated properly)
9hseg

### LINKED ISSUE #1763: Redstone dust doesn't work properly.
When you have a redstone torch powering a line of redstone dust, after disabling the torch, the dust flashes on and off really fast untill it's nearly shut off, but it doesn't shut off because there's still some dust being powered somehow.

It's hard to explain, you need to try it yourself.

Edit:
the Windows x64 build 178 of the server, and I'm running Windows 7 ulti. x64

### LINKED ISSUE #1887: Trapdoors "forget" open/closed state upon server restart
Many times they are used for decoration -

 

... and this is what it looks like when the state they were left in wasn't saved, or saved correctly.
Look at that sad little lantern.... ;)

### LINKED ISSUE #2009: Crossing redstone dust chunk bug
If redstone dust paths are crossing each other, then the dust isn't switching off correctly after turning off the lever. This bug is happening if the redstone dust path crosses chunk borders. Maybe it is related to the direction, so we've found out it's often not working with: south-north; east-west; west-east.

Video: http://youtu.be/d4GnuUxfcZE

### LINKED ISSUE #2191: Redstone not gates not working properly with repeaters nearby
These two are perfectly valid clocks in Vanilla. In MCServer, they simply won't work. I recall a similar issue a very long time ago. Back then, Tiger fixed it, I think.

### PR DESCRIPTION
**Pull request by tigerw**
+ Partially implemented comparators
+ Wires now power on/off simultaneously
* Potential performance improvements
* Improvements to linked powering
* Fixes #1887
* Fixes #1763
* Fixes #1083
* Fixes #2009
* Fixes #2191

### CODE REVIEW

**Comment by NiLSPACE** [comment]
And we're back with the `[SEE DESC]` PR's ;)

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 1]
```diff
@@ -503,152 +514,280 @@ void cIncrementalRedstoneSimulator::HandleRedstoneButton(int a_RelBlockX, int a_
...
+	} CCB;
+
+	auto AbsoluteComparatorCoords = cChunkDef::RelativeToAbsolute(Vector3i(a_RelBlockX, a_RelBlockY, a_RelBlockZ), m_Chunk->GetPosX(), m_Chunk->GetPosZ());
+	auto AbsoluteRearCoords = cBlockComparatorHandler::GetRearCoordinate(AbsoluteComparatorCoords.x, AbsoluteComparatorCoords.y, AbsoluteComparatorCoords.z, Meta & 0x3);
+
+	m_Chunk->DoWithBlockEntityAt(AbsoluteRearCoords.x, AbsoluteRearCoords.y, AbsoluteRearCoords.z, CCB);
+	auto RearPower = std::max(CCB.m_SignalStrength, IsWirePowered(AdjustRelativeCoords(cBlockComparatorHandler::GetRearCoordinate(a_RelBlockX, a_RelBlockY, a_RelBlockZ, Meta & 0x3)), m_Chunk));
+
+	if ((Meta & 0x4) == 0x4)
+	{  // Subtraction mode
```
Comment (NiLSPACE) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Are comments on the braces allowed?

File: src/ChunkDef.h [hunk 2]
```diff
@@ -96,6 +96,25 @@ class cChunkDef
...
+
+	inline static Vector3i AbsoluteToRelative(Vector3i a_BlockPosition, int a_ChunkX, int a_ChunkZ)
+	{
+		return {a_BlockPosition.x - a_ChunkX * Width, a_BlockPosition.y, a_BlockPosition.z - a_ChunkZ * Width};
+	}
+
+	/** Converts relative block coordinates into absolute coordinates with a known chunk location */
+	inline static Vector3i RelativeToAbsolute(const Vector3i & a_RelBlockPosition, int a_ChunkX, int a_ChunkZ)
+	{
+		return Vector3i(a_RelBlockPosition.x + a_ChunkX * Width, a_RelBlockPosition.y, a_RelBlockPosition.z + a_ChunkZ * Width);
```
Comment (worktycho) [inline src/ChunkDef.h]: Why does this function use function style initialization when the other two use uniform initialization?

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 1 above)
Comment (madmaxoft) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Not really

File: src/Simulator/IncrementalRedstoneSimulator.h [hunk 3]
```diff
@@ -348,47 +391,30 @@ class cIncrementalRedstoneSimulator :
...
-		while (RelPos.z < 0)
-		{
-			RelPos.z += cChunkDef::Width;
-		}
-
-		return RelPos;
+	inline static Vector3i AdjustRelativeCoords(const Vector3i & a_RelPosition)
+	{
+		return Vector3i((a_RelPosition.x % cChunkDef::Width + cChunkDef::Width) % cChunkDef::Width, a_RelPosition.y, (a_RelPosition.z % cChunkDef::Width + cChunkDef::Width) % cChunkDef::Width);
 	}
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.h]: What does this do exactly? `x % y + y % y == x %y`

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 4]
```diff
@@ -77,39 +77,53 @@ void cIncrementalRedstoneSimulator::RedstoneAddBlock(int a_BlockX, int a_BlockY,
...
+		SetInvalidMiddleBlock(a_RelBlockPosition.x, a_RelBlockPosition.y, a_RelBlockPosition.z, a_NeighborChunk != nullptr ? a_NeighborChunk : a_OriginalChunk);
+	}
+
+	if (a_NeighborChunk != nullptr)
+	{
+		// DO NOT touch our chunk's data structure if we are being called with coordinates from another chunk - this one caused me massive grief :P
+		return;
+	}
+
+	auto & SimulatedPlayerToggleableBlocks = static_cast<cIncrementalRedstoneSimulatorChunkData *>(a_OriginalChunk->GetRedstoneSimulatorData())->m_SimulatedPlayerToggleableBlocks;
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Since you only every query it for blocks, should m_SimulatedPlayerToggleableBlocks be a map of some kind?

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 5]
```diff
@@ -25,41 +24,42 @@ typedef cItemCallback<cChestEntity> cChestCallback;
...
 {
-	if ((a_Chunk == nullptr) || !a_Chunk->IsValid())
+	AddBlock(cChunkDef::AbsoluteToRelative({ a_BlockX, a_BlockY, a_BlockZ }, a_Chunk->GetPosX(), a_Chunk->GetPosZ()), a_Chunk, nullptr);
+}
+
+
+
+
+
+void cIncrementalRedstoneSimulator::AddBlock(const Vector3i & a_RelBlockPosition, cChunk * a_OriginalChunk, cChunk * a_NeighborChunk)
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: This method is getting too big. Break it up into smaller submethods.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 6]
```diff
@@ -503,152 +514,280 @@ void cIncrementalRedstoneSimulator::HandleRedstoneButton(int a_RelBlockX, int a_
 
 void cIncrementalRedstoneSimulator::HandleRedstoneWire(int a_RelBlockX, int a_RelBlockY, int a_RelBlockZ)
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: This method is too big, so if you're going to make significant changes, split it up

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 7]
```diff
@@ -503,152 +514,280 @@ void cIncrementalRedstoneSimulator::HandleRedstoneButton(int a_RelBlockX, int a_
...
-			continue;
+			return;
 		}
-		if (Type == E_BLOCK_REDSTONE_WIRE)
+
+		if ((Neighbour->GetBlock(AdjustedPos) == E_BLOCK_REDSTONE_WIRE) && (MyPower > 1) && (MyPower > IsWirePowered(AdjustedPos, Neighbour)))
 		{
-			SetBlockPowered(a_RelBlockX + gCrossCoords[i].x, a_RelBlockY + gCrossCoords[i].y, a_RelBlockZ + gCrossCoords[i].z, a_RelBlockX, a_RelBlockY, a_RelBlockZ, MyPower);
+			PowerBorderingWires(a_PotentialWireList, a_Entry, AdjustedPos, Neighbour, MyPower);
 		}
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: This bock should be moved into a seperate method, so you don't repeat yourself for all three loops

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 8]
```diff
@@ -503,152 +514,280 @@ void cIncrementalRedstoneSimulator::HandleRedstoneButton(int a_RelBlockX, int a_
...
-		case REDSTONE_Z_POS:
+	}
+}
+
+
+
+
+
+void cIncrementalRedstoneSimulator::PowerBorderingWires(std::vector<std::pair<Vector3i, cChunk *>> & a_PotentialWireList, const std::pair<Vector3i, cChunk *> & a_Entry, const Vector3i & a_AdjustedPos, cChunk * a_NeighbourChunk, unsigned char a_MyPower)
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: a_Entry has a weird type. Why not separate params?

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 9]
```diff
@@ -503,152 +514,280 @@ void cIncrementalRedstoneSimulator::HandleRedstoneButton(int a_RelBlockX, int a_
...
+{
+	sPoweredBlocks RC;
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Why construct RC if you never use it as an object, only a collection of fields?

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 10]
```diff
@@ -503,152 +514,280 @@ void cIncrementalRedstoneSimulator::HandleRedstoneButton(int a_RelBlockX, int a_
...
+}
+
+
+
+
+
+void cIncrementalRedstoneSimulator::HandleRedstoneComparator(int a_RelBlockX, int a_RelBlockY, int a_RelBlockZ)
+{
+	auto Meta = m_Chunk->GetMeta(a_RelBlockX, a_RelBlockY, a_RelBlockZ);
+	auto HighestSidePower = std::max(IsWirePowered(AdjustRelativeCoords(cBlockComparatorHandler::GetSideCoordinate(a_RelBlockX, a_RelBlockY, a_RelBlockZ, Meta & 0x3, false)), m_Chunk), IsWirePowered(AdjustRelativeCoords(cBlockComparatorHandler::GetSideCoordinate(a_RelBlockX, a_RelBlockY, a_RelBlockZ, Meta & 0x3, true)), m_Chunk));
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: This line is too long, split it up into separate vars.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 11]
```diff
@@ -503,152 +514,280 @@ void cIncrementalRedstoneSimulator::HandleRedstoneButton(int a_RelBlockX, int a_
...
+			return false;
 		}
+
+		unsigned char m_SignalStrength;
+	} CCB;
+
+	auto AbsoluteComparatorCoords = cChunkDef::RelativeToAbsolute(Vector3i(a_RelBlockX, a_RelBlockY, a_RelBlockZ), m_Chunk->GetPosX(), m_Chunk->GetPosZ());
+	auto AbsoluteRearCoords = cBlockComparatorHandler::GetRearCoordinate(AbsoluteComparatorCoords.x, AbsoluteComparatorCoords.y, AbsoluteComparatorCoords.z, Meta & 0x3);
+
+	m_Chunk->DoWithBlockEntityAt(AbsoluteRearCoords.x, AbsoluteRearCoords.y, AbsoluteRearCoords.z, CCB);
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: I think it would be better to refactor DoWithBlockEntityAt to have an overload that takes a lambda, than to write yet another functor object.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 12]
```diff
@@ -503,152 +514,280 @@ void cIncrementalRedstoneSimulator::HandleRedstoneButton(int a_RelBlockX, int a_
...
+	auto RearPower = std::max(CCB.m_SignalStrength, IsWirePowered(AdjustRelativeCoords(cBlockComparatorHandler::GetRearCoordinate(a_RelBlockX, a_RelBlockY, a_RelBlockZ, Meta & 0x3)), m_Chunk));
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: I think the container fetching logic should be moved out into a separate method.

File: src/Simulator/IncrementalRedstoneSimulator.h (hunk 3 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.h]: Isn't it supposed to be ( x % y + y) % y? Since normal mod doesn't produce the wanted result on negative numbers (i.e. -5 % 16 should be 11 for relative adjustment but instead is -5), this is done.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 4 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Then it should be.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 6 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: But I have already, with the FindAndPowerBorderingWires and PowerBorderingWires, no?

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 9 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Does the emplace_back(RC) not count? Or should I use emplace_back to construct an RC?

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 8 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: What would you mean by separate?

File: src/Simulator/IncrementalRedstoneSimulator.h (hunk 3 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.h]: That's what I meant. But you don't need the inner mod, and you should put a comment about negative numbers.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 6 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Its still 70 lines of actual code, which is a bit on the large size.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 8 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Pass a vector3i, and a cChunk * as individual parameters to the function.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 9 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Given that its one emplace in an if, I would go for using emplace_back to construct it.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 13]
```diff
@@ -680,19 +819,50 @@ void cIncrementalRedstoneSimulator::HandleRedstoneRepeater(int a_RelBlockX, int
...
 		else if (!IsSelfPowered && IsOn)  // Queue a power change if unpowered, on, and not locked.
 		{
-			QueueRepeaterPowerChange(a_RelBlockX, a_RelBlockY, a_RelBlockZ, a_Meta, false);
+			QueueRepeaterPowerChange(a_RelBlockX, a_RelBlockY, a_RelBlockZ, Meta, false);
+		}
+	}
+
+	if (IsOn)
+	{
+		switch (Meta & 0x3)  // We only want the direction (bottom) bits
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: This block should be in its own method

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 14]
```diff
@@ -1702,35 +1832,35 @@ bool cIncrementalRedstoneSimulator::IsPistonPowered(int a_RelBlockX, int a_RelBl
...
 
 
-bool cIncrementalRedstoneSimulator::IsWirePowered(int a_RelBlockX, int a_RelBlockY, int a_RelBlockZ, unsigned char & a_PowerLevel)
+unsigned char cIncrementalRedstoneSimulator::IsWirePowered(Vector3i a_RelBlockPosition, cChunk * a_Chunk)
 {
-	a_PowerLevel = 0;
+	unsigned char PowerLevel = 0;
 
-	for (const auto & itr : *m_PoweredBlocks)  // Check powered list
+	for (const auto & itr : static_cast<cIncrementalRedstoneSimulatorChunkData *>(a_Chunk->GetRedstoneSimulatorData())->m_PoweredBlocks)  // Check powered list
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: You should change this list to support querying for a source better.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 15]
```diff
@@ -1702,35 +1832,35 @@ bool cIncrementalRedstoneSimulator::IsPistonPowered(int a_RelBlockX, int a_RelBl
...
+		if (itr.a_BlockPos != a_RelBlockPosition)
 		{
 			continue;
 		}
-		a_PowerLevel = std::max(itr.a_PowerLevel, a_PowerLevel);  // Get the highest power level (a_PowerLevel is initialised already and there CAN be multiple levels for one block)
+		PowerLevel = std::max(itr.a_PowerLevel, PowerLevel);  // Get the highest power level (a_PowerLevel is initialised already and there CAN be multiple levels for one block)
 	}
 
-	for (const auto & itr : *m_LinkedPoweredBlocks)  // Check linked powered list
+	for (const auto & itr : static_cast<cIncrementalRedstoneSimulatorChunkData *>(a_Chunk->GetRedstoneSimulatorData())->m_LinkedBlocks)  // Check linked powered list
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Again this should be changed for better querying.

**Comment by worktycho** [comment]
@tigerw Can you write up a post on the forum about the general architecture of the simulator. Because no one else really understands it, so we can't review your code.

**Comment by tigerw** [comment]
😜

I will try.





From: worktycho
Sent: ‎Thursday‎, ‎28‎ ‎May‎ ‎2015 ‎12‎:‎59
To: mc-server/MCServer
Cc: Tiger Wang





@tigerw Can you write up a post on the forum about the general architecture of the simulator. Because no one else really understands it, so we can't review your code.

**Comment by tigerw** [comment]
Do you think it is a good idea, to reduce the size of IncrementalSim.cpp, to place the various redstone handler functions in their respective BlockHandlers?





From: worktycho
Sent: ‎Thursday‎, ‎28‎ ‎May‎ ‎2015 ‎12‎:‎59
To: mc-server/MCServer
Cc: Tiger Wang





@tigerw Can you write up a post on the forum about the general architecture of the simulator. Because no one else really understands it, so we can't review your code.

**Comment by worktycho** [comment]
I think its a good idea to move things out of IncrementalSim, but I would not move them to the blockHandlers. I would create a separate set of redstoneHandler classes.

**Comment by worktycho** [comment]
@tigerw Can you rebase this onto master?

**Comment by tigerw** [comment]
Yes, though I must need address your comments first.

File: src/Simulator/IncrementalRedstoneSimulator.h (hunk 3 above)
Comment (madmaxoft) [inline src/Simulator/IncrementalRedstoneSimulator.h]: The inner mod is needed, otherwise it doesn't get rid of the negative number. I think the code's correct and it's also the minimum needed.

Comment (madmaxoft) [inline src/Simulator/IncrementalRedstoneSimulator.h]: You might want to consider splitting the long line, each param on a separate line (plus separate line for the closing parenthesis, of course)

**Comment by tigerw** [comment]
Ah, encountering the same problem as #1916. Is there no way no specialise std::hash with GCC/Clang?

**Comment by worktycho** [comment]
Not in the current releases. Use a custom hash object instead.

File: MCServer/Plugins/MagicCarpet [hunk 16]
```diff
@@ -1 +1 @@
-Subproject commit 94da343b62f0498a5843247f36d6ee00cbeb8f21
```
Comment (worktycho) [inline MCServer/Plugins/MagicCarpet]: Why

**Comment by worktycho** [comment]
What are all the note blocks binary files? And if you delete them please remove them from the history compleatly.

File: src/Vector3.h [hunk 17]
```diff
@@ -235,6 +235,12 @@ class Vector3
 		return *this;
 	}
 
+	/** Provides a hash of a vector's contents */
+	size_t operator()(const Vector3<T> & a_Vector) const
```
Comment (worktycho) [inline src/Vector3.h]: Don't make this part of vector3. Either refactor VectorHasher out of aPath as aseperate object, or create one yourself at global scope.

**Comment by madmaxoft** [comment]
@tigerw wants to archive his world and stats on GitHub :)

File: src/Vector3.h (hunk 17 above)
Comment (tigerw) [inline src/Vector3.h]: Why? Who knows when someone might want to hash a vector.

**Comment by tigerw** [comment]
It's my legacy, xoft.

File: src/Vector3.h (hunk 17 above)
Comment (worktycho) [inline src/Vector3.h]: Because why should operator() return the has of a vector? It doesn't make sense. The std lib API is designed so that the hash object should be a seperate object from the data object, so that std::hash works.

Comment (worktycho) [inline src/Vector3.h]: What you should do is create a seperate object, either at global scope, or a sub object of vector3 and use that.

File: src/Vector3.h [hunk 18]
```diff
@@ -235,6 +235,12 @@ class Vector3
...
+	{
+		return ((std::hash<T>()(a_Vector.x) ^ (std::hash<T>()(a_Vector.y) << 1)) ^ std::hash<T>()(a_Vector.z));
```
Comment (worktycho) [inline src/Vector3.h]: This has function is really bad for our dataset, as there will be lots of collisions within a chunk sized area. @SafwatHalaby had a much better hash function for our needs.

Comment (SafwatHalaby) [inline src/Vector3.h]: It's still there, in Path.h

Comment (tigerw) [inline src/Vector3.h]: How do you get a figure for the number of collisions?

Comment (worktycho) [inline src/Vector3.h]: Reasoning about the entropy and trying to force a collision. Within a chunk, the four bits of entropy in each of the X and Z direction is concentrated in the lower order bits. You squash all that entropy into 5 bits.

Comment (tigerw) [inline src/Vector3.h]: Can I improve this by shifting more?

Comment (worktycho) [inline src/Vector3.h]: And then you end up with the hash function safwat used, just use the existing hash function.

Comment (SafwatHalaby) [inline src/Vector3.h]: Perhaps we should migrate it from Path.h to Vector.h so that everybody uses it. It originally belonged there. (But clang complained about something, I think?)

Comment (worktycho) [inline src/Vector3.h]: That's what I  think, but as a separate object, not part of cVector3. The clang error was from specializing std::hash which we wouldn't be doing.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 19]
```diff
@@ -77,68 +77,60 @@ void cIncrementalRedstoneSimulator::RedstoneAddBlock(int a_BlockX, int a_BlockY,
...
-				itr.DataTwo = false;
-				itr.Data = Block;  // Update block information
-			}
-			return;
-		}
+		// Initialise the toggleable blocks list so that trapdoors etc. aren't reset on restart (#1887)
+		SimulatedPlayerToggleableBlocks.emplace(
+			a_RelBlockPosition,
+			AreCoordsDirectlyPowered(a_RelBlockPosition.x, a_RelBlockPosition.y, a_RelBlockPosition.z, a_OriginalChunk) || AreCoordsLinkedPowered(a_RelBlockPosition.x, a_RelBlockPosition.y, a_RelBlockPosition.z, a_OriginalChunk)
+			);  // This map won't insert if key already present, so no need to check
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: You should make AreCoordsDirectlyPowered and AreCoordsLinkedPowered take a vector.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 20]
```diff
@@ -77,68 +77,60 @@ void cIncrementalRedstoneSimulator::RedstoneAddBlock(int a_BlockX, int a_BlockY,
...
+	{
+		SimulatedPlayerToggleableBlocks.erase(a_RelBlockPosition);
+	}
+
+	if ((Block != E_BLOCK_REDSTONE_REPEATER_ON) && (Block != E_BLOCK_REDSTONE_REPEATER_OFF))
+	{
+		static_cast<cIncrementalRedstoneSimulatorChunkData *>(a_OriginalChunk->GetRedstoneSimulatorData())->m_RepeatersDelayList.erase(a_RelBlockPosition);
 	}
 
+	auto & RedstoneSimulatorChunkData = static_cast<cIncrementalRedstoneSimulatorChunkData *>(a_OriginalChunk->GetRedstoneSimulatorData())->m_ChunkData;
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: You should move the ChunkData get above the if, so you don't have to fetch it twice.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 19 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: In another PR I will aim to convert the simulator to use `Vector3i` :)

File: src/Simulator/IncrementalRedstoneSimulator.h [hunk 21]
```diff
@@ -107,126 +98,171 @@ class cIncrementalRedstoneSimulator :
...
 	/** Handles tripwires */
 	void HandleTripwire(int a_RelBlockX, int a_RelBlockY, int a_RelBlockZ);
-	/* ===================== */
 
-	/* ====== Helper functions ====== */
+
 	/** Marks a block as powered */
-	void SetBlockPowered(int a_RelBlockX, int a_RelBlockY, int a_RelBlockZ, int a_RelSourceX, int a_RelSourceY, int a_RelSourceZ, unsigned char a_PowerLevel = MAX_POWER_LEVEL);
+	void SetBlockPowered(Vector3i a_RelBlockPosition, Vector3i a_RelSourcePosition, unsigned char a_PowerLevel = MAX_POWER_LEVEL);
+	void SetBlockPowered(int a_RelBlockX, int a_RelBlockY, int a_RelBlockZ, int a_RelSourceX, int a_RelSourceY, int a_RelSourceZ, unsigned char a_PowerLevel = MAX_POWER_LEVEL) { SetBlockPowered(Vector3i(a_RelBlockX, a_RelBlockY, a_RelBlockZ), Vector3i(a_RelSourceX, a_RelSourceY, a_RelSourceZ), a_PowerLevel); }
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.h]: Why do you still have this overload? How many clients does this function have?

**Comment by tigerw** [comment]
About the style checker, I disagree that

```cpp
return
{
   1, 2, 3
}
```
should be favoured over
```cpp
return {
    1, 2, 3
}
```
since we use
```cpp
if (
   (1 == 1) &&
   (2 == 2)
)
{
}
```
as opposed to
```cpp
if
(
   ...
)
{
}
```

File: src/Simulator/IncrementalRedstoneSimulator.h [hunk 22]
```diff
@@ -107,126 +98,171 @@ class cIncrementalRedstoneSimulator :
...
+
+	/** Recursively searches for a wire path and powers everything that should be powered */
+	void FindAndPowerBorderingWires(std::vector<std::pair<Vector3i, cChunk *>> & a_PotentialWireList, const Vector3i & a_EntryRelBlockPosition, cChunk * a_EntryChunk);
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.h]: What exactly do these pairs hold?

File: src/Simulator/IncrementalRedstoneSimulator.h (hunk 21 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.h]: The int overload? I will check.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 19 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Well you should still change it to use AreCoordsPowered.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 23]
```diff
@@ -77,68 +77,60 @@ void cIncrementalRedstoneSimulator::RedstoneAddBlock(int a_BlockX, int a_BlockY,
...
-	cCoordWithBlockAndBoolVector & QueuedData = ((cIncrementalRedstoneSimulator::cIncrementalRedstoneSimulatorChunkData *)a_Chunk->GetRedstoneSimulatorData())->m_QueuedChunkData;
-	for (const auto & itr : QueuedData)
+	else
 	{
-		if ((itr.x == RelX) && (itr.y == a_BlockY) && (itr.z == RelZ))
+		if (Iterator != RedstoneSimulatorChunkData.end())
 		{
-			// Can't have duplicates in here either, in case something adds the block again before the structure can written to the main chunk data
+			Iterator->second.second = false;
+			Iterator->second.first = Block;  // Update block information
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: I have no idea what this code is doing, which is why you should avoid std::pair here.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 24]
```diff
@@ -185,24 +169,24 @@ void cIncrementalRedstoneSimulator::SimulateChunk(std::chrono::milliseconds a_Dt
...
 	{
-		if (dataitr->DataTwo)
+		if (dataitr->second.second)
 		{
 			dataitr = m_RedstoneSimulatorChunkData->m_ChunkData.erase(dataitr);
 			continue;
 		}
 
-		switch (dataitr->Data)
+		switch (dataitr->second.first)
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: This huge switch should really be replaced with a lookup table, but I suspect that's out of scope for this PR.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 19 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Ah, but that doesn't take a cChunk.

Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: There is way too much complexity here then.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 25]
```diff
@@ -77,68 +77,60 @@ void cIncrementalRedstoneSimulator::RedstoneAddBlock(int a_BlockX, int a_BlockY,
...
-				itr.DataTwo = true;  // The new blocktype is not redstone; it must be queued to be removed from this list
-			}
-			else
-			{
-				itr.DataTwo = false;
-				itr.Data = Block;  // Update block information
-			}
-			return;
-		}
+		// Initialise the toggleable blocks list so that trapdoors etc. aren't reset on restart (#1887)
```
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Anytime you write a comment: this block does x, it indicates the block should be a separate method.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 23 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Must you know? Not using a pair means another struct to wrap the two members for map storage. I have too many structs already :/

Would a comment where the map is defined satisfy you?

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 25 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: I am trying to keep the size of IncrementalSim.cpp down, especially with the requirement of 5 lines between functions, and not having much time to split the file.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 23 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: You have too many structs because you have too much logic in one class. std::pair only hides the root problem which is that cIncrementalRedstoneSimulator is a good object, whilst making the code even more confusing.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 25 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: That is a bad goal. If you don't have time to split the object, don't try to keep the size down, as that just leads to more confusing code. The only way to reduce the size of cIncrementalSim is to split the object.

Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: But I don't really see how in this case, adding another function will affect clarity. The block isn't long, nor is it used anywhere else. Moving the block into a method for the sake of it will at most replace this comment.

Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Then either the code is unclear and should be rewritten for increased clarity, or the comment is unnecessary. I suspect that in this case its the first one due to the data-structures of the sim being too complicated.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 23 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: But comments de-confuse pairs?

cIncrementalRedstoneSim is a god object because it's a redstone simulator, no? Would you have separate classes for every redstone device it simulates, and 10+ additional files?

Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: No comments do not. And yes having 10 additional files is superior to the current situation, because when working out whats going on, you only have to look at a subset of the code.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 25 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Then how would you uncomplicate it?

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 23 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Why do comments not? `Iterator->second.second = false; // De-schedule entry removal`

Having more files arguably doesn't reduce complexity, good commenting does.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 25 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Split the object.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 23 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Its still completely unclear how the code is doing that, comments do not substitute clean code.

Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: No, but good commenting doesn't reduce complexity either. What multiple files do is allow you to ignore complexity that is not relevant to the problem you are working on.

Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Okay, but I do not understand how it is unclear how the code is working, nor how adding files instead of comments will explain the iterator invalidation problems that necessitate using std::pair.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 25 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Or for now another method?

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 23 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Its the fact that the pair fields have no name, that Iterator->second.second = false; means nothing.

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 25 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: I think we're either going to have to leave it for now, or draw a line and say we're not accepting any more feature PR's until the sim is split. I can't make that decision on my own @madmaxoft Whats your opinion?

Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Unless a comment goes along with it?

File: src/Simulator/IncrementalRedstoneSimulator.cpp (hunk 23 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Unless a comment goes along with it?

Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: In every single location, which is much more work then just creating a struct with names.

Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: And then it becomes a matter of preference, especially since it's only used in two places.

File: src/Simulator/IncrementalRedstoneSimulator.h (hunk 21 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.h]: Around 10.

**Comment by tigerw** [comment]
Merge?

File: src/Simulator/IncrementalRedstoneSimulator.h (hunk 21 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.h]: You should refactor them to use the vector version.

**Comment by worktycho** [comment]
I'm not going to merge this because you haven't addressed all my comments.

File: src/Simulator/IncrementalRedstoneSimulator.h (hunk 21 above)
Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.h]: In another PR?

**Comment by tigerw** [comment]
About std::pair:
I still don't fully agree with your recommendations. If a structure is used, the descriptiveness of the members would be that of `m_BlockType` and `m_Chunk`. In a pair, this would be given as BLOCKTYPE and cChunk by either reading the declaration or by the IDE. If one wanted to know what they did, one would still need to explore further.

About splitting large functions and the file in general:
I agree this is a good idea, but this pull request is already quite large and isn't relevant to it. I will be sure to do so sometime in the future.

File: src/Simulator/IncrementalRedstoneSimulator.h (hunk 21 above)
Comment (worktycho) [inline src/Simulator/IncrementalRedstoneSimulator.h]: That wont happen. Seriously you need to finish any refactors in this PR, unless its a public method thats used in lots of places.

**Comment by worktycho** [comment]
I'm just not going to merge this. But I won't object if someone else does.

**Comment by tigerw** [comment]
:/

**Comment by tigerw** [comment]
I view of the guideline not to add unrelated changes to requests, what would you like me to do? Neither std::pair nor splitting have anything to do with performance/bug fixes, which are the primary concern of this request.

Are you sure this can't go in? None of the issues mentioned are being caused by these changes, merely raised by them.

**Comment by worktycho** [comment]
If making a refactor would improve the code you're changing, make it part of the PR. Otherwise the refactors never happen. The problem is adding multiple feature/bug fixes to a PR, which you keep doing.

**Comment by worktycho** [comment]
Also, whilst the changes do not cause a lot of the problems, they exacerbate them, which brings those problems in scope.

**Comment by tigerw** [comment]
Could I sway you if I promise to refactor after exams?

**Comment by worktycho** [comment]
No

**Comment by tigerw** [comment]
Well.

That's that.

No

**Comment by bearbin** [comment]
Merging, as I don't think it's likely tiger is going to refactor for a few weeks, due to exams. A proper refactoring of the redstone code should hopefully follow.

File: src/Simulator/IncrementalRedstoneSimulator.cpp [hunk 26]
```diff
@@ -503,152 +486,278 @@ void cIncrementalRedstoneSimulator::HandleRedstoneButton(int a_RelBlockX, int a_
...
+				case E_BLOCK_REDSTONE_REPEATER_OFF:
+				{
+					BorderingMechanismCount++;
+					if (!RepeaterPresent)
+					{
+						// TODO: only if wire is actually connected to repeater (repeater facing right way)
+						RepeaterPresent = true;
+						OffsetToPower = { -Offset.x, Offset.y, -Offset.z };  // Negate to obtain offset in opposite direction since wire powers that way
+					}
+					SetBlockPowered(AdjustedOffset, RelBlock, MyPower);
```
Comment (madmaxoft) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Shouldn't there be a `break` here?

Comment (tigerw) [inline src/Simulator/IncrementalRedstoneSimulator.cpp]: Looks like it, though (thankfully) it hasn't manifested as a bug yet.
