### PR TITLE
Fix gamemode not changing properly.

### LINKED ISSUE #604: Players can be left floating if gameMode changes from creative to survival
1. A player is flying in creative mode
2. The server is shut down and switched to survival
3. The player will still be flying and cannot disable flymode

The player is stuck in flymode forever.

### PR DESCRIPTION
**Pull request by bearbin**
Should fix #604

### CODE REVIEW

File: src/Entities/Player.cpp [hunk 1]
```diff
@@ -1231,6 +1231,21 @@ void cPlayer::SetGameMode(eGameMode a_GameMode)
...
 {
 	m_GameMode = a_GameMode;
+	
+	if (!(IsGameModeCreative() || IsGameModeSpectator()))
+	{
+		SetFlying(false);
+		SetCanFly(false);
+	}
+
+	if (IsGameModeSpectator() && IsVisible())
```
Comment (tigerw) [inline src/Entities/Player.cpp]: I'm not sure if this is how spectator works, but if a player is in spectator mode and they aren't visible (normal presumably?), does that mean it will fall through to the else if and set them to be visible?

Comment (bearbin) [inline src/Entities/Player.cpp]: You're right. This is a logic error.

Comment (bearbin) [inline src/Entities/Player.cpp]: Fixed.

**Comment by bearbin** [comment]
It seems my editor has automatically cleaned up some whitespace but it shouldn't be an issue.

File: src/Entities/Player.cpp [hunk 2]
```diff
@@ -1231,6 +1218,30 @@ void cPlayer::SetGameMode(eGameMode a_GameMode)
...
+
+void cPlayer::SetCapabilities()
+{
+	if (!IsGameModeCreative() || IsGameModeSpectator())
+	{
+		SetFlying(false);
+		SetCanFly(false);
+	}
+
+	if (!IsGameModeSpectator() && !IsVisible())
```
Comment (tigerw) [inline src/Entities/Player.cpp]: Would:

```cpp
if (IsGameModeSpectator())
{
    SetVisible(false);
}
else
{
    SetVisible(true);
}
```

work?

Comment (bearbin) [inline src/Entities/Player.cpp]: Probably, I'm just not sure of the side-effects of calling SetVisible and calling it again for a player who's already in the state they are being set to may have unintended consequences (performance, client bugs, etc).

Comment (bearbin) [inline src/Entities/Player.cpp]: I just checked and that code would work. Amending the commit now.

File: src/Entities/Player.cpp [hunk 3]
```diff
@@ -1196,30 +1196,17 @@ void cPlayer::SetGameMode(eGameMode a_GameMode)
...
-	
+
 	if (m_GameMode == a_GameMode)
 	{
 		// Gamemode already set
 		return;
 	}
-	
+
 	m_GameMode = a_GameMode;
```
Comment (SafwatHalaby) [inline src/Entities/Player.cpp]: beep
