### PR TITLE
Fix slab placing

### LINKED ISSUE #1837: Slab placing
There are a few bugs when placing slabs.

If I place a slab beneath another slab which is on half block height two slabs were built. One to complete the Block and one more under the full block.

If I want to place a slab in the half block space between a slab on half block height with a full block under it and point the upper side of the block below, the slab will not appear.

And if I want to put a slab on the top of another slab no sound is played and this slaps sometimes disappear (maybe 1 of 20).

### PR DESCRIPTION
**Pull request by wraith11**
fix #1837

### CODE REVIEW

File: src/Items/ItemSlab.h [hunk 1]
```diff
@@ -63,11 +69,28 @@ class cItemSlabHandler:
 				((ClickedBlockMeta & 0x08) != 0)
 			)
 			{
+				a_World.BroadcastSoundEffect(PlaceSound, a_BlockX + 0.5, a_BlockY + 0.5, a_BlockZ + 0.5, Volume, Pitch);
 				return a_Player.PlaceBlock(a_BlockX, a_BlockY, a_BlockZ, m_DoubleSlabBlockType, ClickedBlockMeta & 0x07);
 			}
 		}
 
+		// Checking the type of block that should be placed
```
Comment (worktycho) [inline src/Items/ItemSlab.h]: Theres one extra space one the end of this line which is being flagged by the build server.

Comment (wraith11) [inline src/Items/ItemSlab.h]: A space in a comment, really? Think this is a bit strict.

Comment (worktycho) [inline src/Items/ItemSlab.h]: The rule used is very simple, white space followed by a new line because lua patterns can't tell if you're in a comment.

File: src/Items/ItemSlab.h [hunk 2]
```diff
@@ -63,11 +69,28 @@ class cItemSlabHandler:
...
+		AddFaceDirection(a_BlockX, a_BlockY, a_BlockZ, a_BlockFace);
```
Comment (madmaxoft) [inline src/Items/ItemSlab.h]: I'd have preferred if you used a separate set of coords, `PlacedBlockX`, `PlacedBlockY` and `PlacedBlockZ`, and keep the values of `a_BlockX` et al.

File: src/Items/ItemSlab.h [hunk 3]
```diff
@@ -63,11 +69,28 @@ class cItemSlabHandler:
...
+		BLOCKTYPE PlaceBlockType;
+		NIBBLETYPE PlaceBlockMeta;
+		a_World.GetBlockTypeMeta(a_BlockX, a_BlockY, a_BlockZ, PlaceBlockType, PlaceBlockMeta);
+		// If it's a slab combine into a doubleslab (means that clicked on side, top or bottom of a block adjacent to a half slab)
+		if (
+			(PlaceBlockType == m_ItemType) &&                         // Placing the same slab material
+			((PlaceBlockMeta & 0x07) == a_EquippedItem.m_ItemDamage)  // Placing the same slab sub-kind (and existing slab is single)
```
Comment (madmaxoft) [inline src/Items/ItemSlab.h]: This doesn't check the single-slabbed-ness at all. The `PlaceBlockType` check (above) does that, because double-slabs have a different block type

**Comment by madmaxoft** [comment]
It'd be great if you could squash all of the commits into a single one, so that we don't have the "deleted whitespace" commits in the main history.

**Comment by wraith11** [comment]
done
