### PR TITLE
Fix door placing in connection with slabs

### LINKED ISSUE #1849: Doors can't be placed on top-half slabs
If a door is placed on a top-half slab only a client sided door appears.

### PR DESCRIPTION
**Pull request by wraith11**
Exclude top-half slabs as transparent blocks for doors. 
fixes #1849

### CODE REVIEW

**Comment by tigerw** [comment]
Try replacing the calls to cWorld::GetMeta to cWorld::GetBlockMeta?

File: src/Blocks/BlockDoor.h [hunk 1]
```diff
@@ -109,15 +109,25 @@ class cBlockDoorHandler :
...
 
 
 	/** Returns true if door can be placed on the specified block type. */
-	static bool CanBeOn(BLOCKTYPE a_BlockType)
+	static bool CanBeOn(BLOCKTYPE a_BlockType, NIBBLETYPE a_BlockMeta)
 	{
-		// Vanilla refuses to place doors on transparent blocks
+		// Vanilla refuses to place doors on transparent blocks, except top-half slabs and other doors
 		// We need to keep the door compatible with itself, otherwise the top half drops while the bottom half stays
+		switch (a_BlockType)
```
Comment (tigerw) [inline src/Blocks/BlockDoor.h]: You can do `return cBlockSlabHandler::IsAnySlabType(a_BlockType) && ((a_BlockMeta & 0x08) != 0)`.

Comment (madmaxoft) [inline src/Blocks/BlockDoor.h]: The condition would be growing to unmaintainable lengths, I think I'd prefer a simple 
```cpp
// Doors can be placed on upside-down slabs:
if (cBlockSlabHandler::IsAnySlabType(a_BlockType) && ((a_BlockMeta & 0x08) != 0))
{
  return true
}
```

**Comment by wraith11** [comment]
>Try replacing the calls to cWorld::GetMeta to cWorld::GetBlockMeta?

yes, that's what I wanted to do :laughing: 
I was just too tired yesterday. Every time I commited my changes and the build fails I noticed that I'm not even finished. Finally I just closed the pull request and go to sleep. 
Next day I tried to fixt it in 3 minutes :laughing: 
I really should take some more time out if I want accomplish something.

>You may also prepend:

```close
closes
closed
fix
fixes
fixed
resolve
resolves
resolved
```
thanks

**Comment by madmaxoft** [comment]
It almost seems as if you don't compile the source yourself. Do you? How would you test the changes without compiling locally?

**Comment by madmaxoft** [comment]
Alright, now the code looks alright, could you squish your commits into a single one, please?

**Comment by wraith11** [comment]
You're right, I havn't tested that code locally but I mean to do it. I just had no time to search and install a appropriate compiler but I want to hear your conments.
After this weekend I may have some more time.

Do I have to do a New pull request to squish the commits?

**Comment by madmaxoft** [comment]
No, you don't need to start a new PR. Just use `git rebase --interactive` in your local repo to squish the commits, then force-push the branch to your GitHub repo; the PR will get updated automatically.

As for compiler - either use gcc / clang if on Linux, or MS Visual Studio Community Edition 2013 if on Windows.

**Comment by wraith11** [comment]
Squished and tested. Works well but I found other bugs with doors.. 
- You can't place doors on snow
- No sound is played when build
- Oak doors will always collected in a new slot
